### ISSUE TITLE
Process automation

### ISSUE THREAD

**Issue by paddelia1** [m-kovalsky/ProcessingManager#1]
HI,
How do I automate this using a scheduler such as SQL Server Agent, or Automic or Control M or Active Batch?
can I schedule some PowerShell script or otherwise embed the execution script? 
Can is call this from a task within a SSIS workflow?
Any of the above as either asynchronous or synchronous?
Can I get the error log raised to the caller for reporting when there is an issue?
Thanks

**Comment by m-kovalsky** [comment]
Hi,
You can run the command line code in many systems (sql server agent, SSIS etc.). I'm not familiar with some of the other programs but if they can run command line code then you can use them as well.

https://docs.microsoft.com/sql/integration-services/control-flow/execute-process-task?view=sql-server-ver15

Also, if you use the -V -E -W it will output the error logs to your system (as specified in my blog post).
https://www.elegantbi.com/post/processingmanager
