### ISSUE TITLE
Cannot only process partitions

### ISSUE THREAD

**Issue by GilbertQue** [m-kovalsky/ProcessingManager#3]
Hi there Michael, thanks for a wonderful tool.

I am trying to just process 2 partitions in PPU in the Power BI Service and when I try and save it from the Window it says I need to select a table as shown below.

![image](https://user-images.githubusercontent.com/72849240/135357726-1f8e3457-2793-4473-9915-b47e18f27bc3.png)

If you could please have a look at this.

What I am looking to do, is to process just the incremental partitions in a PPU instance.

Thanks
Gilbert

**Comment by m-kovalsky** [comment]
This is fixed in [v1.1.2](https://github.com/m-kovalsky/ProcessingManager/releases/tag/1.1.2). Thanks for reporting!
